### ISSUE TITLE
final variable can't be null?

### ISSUE THREAD

**Issue by stdweird** [quattor/pan#93] opened 2015-07-29 18:34 UTC
``` pan
object template example2;                                                                                                                             

final variable TEST = 'x';                                                                                                                            
variable TEST ?= 'something';                                                                                                                         

final variable TEST2 = null;                                                                                                                          
variable TEST2 ?= 'something';          
```

output (`TEST` is ok, `TEST2` not)

```
evaluation error [/home/stdweird/pan/example2.pan:7.1-7.30]                                                                                           
cannot modify final global variable                                                                                                                   
>>> call stack trace                                                                                                                                  
>>> [/home/stdweird/pan/example2.pan:7.1-7.30]                                                                                                        
>>> ====================            
```

**Comment by ned21** [comment] 2015-07-29 21:11
What's your expected behaviour? final means it cannot be changed and setting it to null is a change?

**Comment by stdweird** [comment] 2015-07-30 05:11
@ned21 i expect the following to compile
```pan
final variable TEST2 = null;
variable TEST2 ?= "something";
```

the default should not be assigned, so `TEST2` is `null`. playing with it a bit more, it actually already fails on 
```pan
object template example3;
variable TEST3 = null;
variable TEST3 ?= "x";
"/a" = TEST3;
```

gives
```
[stdweird@localhost pan]$ panc example3.pan 
[stdweird@localhost pan]$ cat example3.xml 
<?xml version="1.0" encoding="UTF-8"?><nlist format="pan" name="profile">
    <string name="a">x</string>
</nlist>
```
while i expected this to be empty.


so this probably has nothing to do with `final`, but rather with default assigmnet and the `null` value. i expect that default assigment works like this for `undef` value, but not for `null`.

**Comment by iliclaey** [comment] 2016-07-28 14:40
While testing, this is what I found.
When setting a final variable to `null` or `undef`, `is_defined` results to false and `exists` results to true in both cases.

In the TEST3-case, the reason "/a" is not empty is because `null` deletes the variable, even though it still supposedly exists.

**Comment by jouvin** [comment] 2017-11-08 12:43
Oooppsss, sorry for not jumping into this one sooner, I just saw #175 and that raised my attention. I'm afraid there is something wrong in the change: a good test would be to compile the template library examples before and after the change and check it everything is the same... As for me, `null` must be handled as a special value when it comes to variable assignments. The reason is that you want to be able to do things like:
```
variable A = null;
variable B = A;
```
expecting `B` to be `null`. For this to happen, you need `null` to be a value assigned to variable `A` when you'd expect that for a configuration path, it will delete it.
I'd say that if to implement the change, you have to modify a unit test, you are probably doing something wrong... The unit test has probably been added to cover a case!

**Comment by stdweird** [comment] 2017-11-08 13:04
@jouvin this issue is about default assigments, your example should still work. i'll add a unittest for it to make sure

**Comment by jouvin** [comment] 2017-11-08 13:07
@stdweird why only about default assignments? I think it should work equally for default or standard assignment...

**Comment by stdweird** [comment] 2017-11-08 13:17
because it's now broken for the default assignment, not for the regular use (the title is misleading, the real issue is the example3 in https://github.com/quattor/pan/issues/93#issuecomment-126184663)

**Comment by jouvin** [comment] 2017-11-08 13:24
Ok then... despite I am not totally convinced at this stage! I don't have the time to look at it more today... but again, one test to run to assess the change is correct is compiling the template library example, comparing the resulting profiles with and without the PR...

**Comment by stdweird** [comment] 2017-11-08 14:02
@jouvin i added unittest variable16. is that what you want to verify?

**Comment by jouvin** [comment] 2017-11-08 14:09
@stdweird yes but we also need the same with default values (or is it already there)?

**Comment by stdweird** [comment] 2017-11-08 14:10
you mean 
```pan
variable A?= null
variable B ?= A;
```

**Comment by ned21** [comment] 2017-11-09 10:39
@stdweird Sorry I missed your 2015 comment about expected behaviour. In the case of

```
variable TEST2 = null;
variable TEST2 ?= "something";
```

I would expect ```TEST2 = "something"``` because the expected behaviour of assigning null is to delete the variable (i.e. make it as if it never existed). So what should happen if you call:

```
final variable TEST2 = null;
```
?

I can see three possible cases:
1. final is an impossible state - compile error
2. final is redundant/meaningless - ignore it and treat as if it wasn't there
3. make it so further use of TEST2 is impossible

(3) just sounds complex and confusing. (2) means ignoring something the PAN developer wrote and acting as if the compiler knows better which is rarely a good idea, so I vote for (1).

**Comment by stdweird** [comment] 2017-11-09 10:44
@ned21 lets not complicate things with `final` 😄 
so the following 
```
variable A = null;
"/a" = exists(A);
```
should result in what?

**Comment by stdweird** [comment] 2017-11-09 10:50
@ned21 heh, i never knew this. the panbook has `The null value deletes the path or global variable to which it is assigned. Most operations and functions will report an error if this value is processed directly.`
so @jouvin  code 
```
variable A = null;
variable B = A;
```
should give some exception?

**Comment by stdweird** [comment] 2017-11-09 10:54
pffff, `exists` function has `If the argument is a variable expression (with or without subscripts) then this function will return true if the given variable exists; the value of referenced variable is not used. ` 
so no special meaning to `null` or anything.

**Comment by ned21** [comment] 2017-11-09 11:08
> should give some exception?

@stdweird Correct. The error for 

```
1: variable A = null;
2: variable B = A;
```

should be the same as for the code:

```
1: variable B = A;
```

**Comment by stdweird** [comment] 2017-11-09 11:13
@ned21 ok, that is really not the case now. there's nothing in the panc code that treats null specially wrt variables, except for the default assignment (and the panbook stating that it is special). even `exists` reports the variable as existing.

but i'd rather edit the panbook and merge #175, because it is much closer to what the code is doing.

**Comment by stdweird** [comment] 2017-11-09 12:07
@ned21 the issue was only wrt the default assigment, and panbook says `For the conditional form, the DML block will only be evaluated and the assignment done if the variable does not exist or has the undef value.`
so `null` has no special meaning in that context (as a value of a variable that does exist).

so the big question is: `variable A = null` does it follow panbook or the current code?

i also would like to see some usage examples oof `variable A = null` that do something with current compiler and rely on the behaviour from panbook. i guess the default assigmnet would be the only one?

**Comment by jrha** [comment] 2017-11-09 12:25
I think we should update the documentation to match the behaviour, fixing this now could potential break a lot of existing code.

**Comment by ned21** [comment] 2017-11-09 18:05
hmm.. My expectation is that:

```
variable A = null;
"/a" = exists(A);
```

Should return false. So if you are saying that's not true then I am 😭 because it makes null act the same as undef for variables except in the case of the default values as you point out. (Is the real answer here to use fewer globals? 😉)

So, maybe @jouvin is correct, and for global variables, `null` should be treated like any other value, with transitive assignment? In other words:
```
variable A = null;
variable A ?= "foo";
variable B = A;
"/b" = B;
```

should have the same effect as `"/b" = null;` ?

**Comment by stdweird** [comment] 2017-11-09 18:38
@ned21 if #175 is merged, yes.
our original issue is that we have a 
```pan
variable X ?= 'some/template'
include X;
```
and without #175, we cannot do `final variable X = null` to prevent the `include`.

i can extend #175 to remove the panbook reference wrt global variables and null removing them in https://github.com/quattor/pan/blob/master/panc-docs/source/pan-book/pan-book.rst#special-types

**Comment by jouvin** [comment] 2017-11-12 18:58
Yes. and may be `B = A;`.

**Comment by jouvin** [comment] 2017-11-12 19:05
Sorry for the very late response to https://github.com/quattor/pan/issues/93#issuecomment-343118314... I'm really not much available these days and it will probably last one or 2 weeks at least... But clearly, @stdweird , you were may be not available of this feature and it seems it was not properly documented but it was very intentionally introduced for the reason I explained. I understand your use case with `final` but I think this is clearly a change that deserves more discussion, probably at next workshop... This is a pitty that the issue was not raised/discussed at the last workshop (or I missed it).

**Comment by stdweird** [comment] 2017-11-13 08:37
@jouvin i don't follow what you mean? there is yet another implied/assumed/undocumneted behaviour with null? if you have some smaple pan code that you want tested, feel free to add it here, but afaik, the current behaviour is what you wanted.
we can hold off merging #175 until you find some time to join the standup and we can discuss it.

**Comment by ned21** [comment] 2017-11-14 20:26
+1: I also think this now matches the behaviour @jouvin describes. Having said that, I do now realise that the exists9.pan tests are changing in a subtle way, from ?= to = which may be more of a concern. Is that right?

**Closed** 2018-04-07 13:46 UTC
