### ISSUE TITLE
panlint: bogus report on component path in value()

### ISSUE THREAD

**Issue by wdpypere** [quattor/pan#227] opened 2019-11-21 10:58 UTC
we get someting like this

```
Component <COMP> in use, but component config has not been included
variable VARIABLE = value("/software/components/<COMP>/something");
```

I don't think it should report on this components path that the component is in use.

**Comment by jrha** [comment] 2019-12-09 10:14
Seems like a duplicate of #226.

**Closed by jrha** 2019-12-09 10:14 UTC
Labels: duplicate
